name: manage-azure-policy-77c0270d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Disk_encryption_should_be_enabled_on_Azure_Data_Explorer_f4b53539-8df9-40e4-86c6-6b607703bd4e/**'
#      - 'policies/Azure_Data_Explorer_encryption_at_rest_should_use_a_customer-managed_key_81e74cea-30fd-40d5-802f-d72103c2aaaa/**'
#      - 'policies/App_Configuration_should_use_private_link_ca610c1d-041c-4332-9d88-7ed3094967c7/**'
#      - 'policies/Double_encryption_should_be_enabled_on_Azure_Data_Explorer_ec068d99-e9c7-401f-8cef-5bdde4e6ccf1/**'
#      - 'policies/App_Configuration_should_use_a_customer-managed_key_967a4b4b-2da9-43c1-b7d0-f98d0d74d0b1/**'
#      - 'policies/Deploy_Log_Analytics_agent_for_Linux_virtual_machine_scale_sets_5ee9e9ed-0b42-41b7-8c9c-3cfb2fbe2069/**'
#      - 'policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'policies/Azure_Stream_Analytics_jobs_should_use_customer-managed_keys_to_encrypt_data_87ba29ef-1ab3-4d82-b763-87fcd4f531f7/**'
#      - .github/workflows/manage-azure-policy-77c0270d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_77c0270d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Disk_encryption_should_be_enabled_on_Azure_Data_Explorer_f4b53539-8df9-40e4-86c6-6b607703bd4e/**
          policies/Azure_Data_Explorer_encryption_at_rest_should_use_a_customer-managed_key_81e74cea-30fd-40d5-802f-d72103c2aaaa/**
          policies/App_Configuration_should_use_private_link_ca610c1d-041c-4332-9d88-7ed3094967c7/**
          policies/Double_encryption_should_be_enabled_on_Azure_Data_Explorer_ec068d99-e9c7-401f-8cef-5bdde4e6ccf1/**
          policies/App_Configuration_should_use_a_customer-managed_key_967a4b4b-2da9-43c1-b7d0-f98d0d74d0b1/**
          policies/Deploy_Log_Analytics_agent_for_Linux_virtual_machine_scale_sets_5ee9e9ed-0b42-41b7-8c9c-3cfb2fbe2069/**
          policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          policies/Azure_Stream_Analytics_jobs_should_use_customer-managed_keys_to_encrypt_data_87ba29ef-1ab3-4d82-b763-87fcd4f531f7/**
